### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by FezVrasta** [XanderStrike/plaxt#1]
Hi, I tried your service but it doesn't seem to do anything.

I tried to play a movie on Plex and nothing is shown on Trakt

**Comment by thespacedoctor** [comment]
I would like to know too - tried on Plex Cloud account, but nothing shows up in Trakt. Would be lovely if it did work! :)

**Comment by jimbob1001** [comment]
It did work, but seems to have stopped for me on the 8th January, as that is my last scrobbled date. Wonder what happened?

**Comment by thespacedoctor** [comment]
I did some experimenting with webhooks added to my plex cloud account and they don't trigger with any of my plex activity. Plex state in their current FAQ (January 29, 2018) that webhooks aren't supported in cloud accounts yet:

https://support.plex.tv/articles/226825168-faq-plex-cloud/

**Comment by XanderStrike** [comment]
Hey y'all, sorry for the radio silence. Trakt changed some things about how tokens age that borked the app.

Rather than update this mess, I went ahead and rewrote it in an entirely different language. Such is the life of a personal project 😐 

If you'd like to help beta test it, it's up and running at https://plaxt.astandke.com

Please send me any issues you have at the new repo: https://github.com/XanderStrike/goplaxt/
